/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as timeLockSol from "./TimeLock.sol";
export { GovernorContract__factory } from "./GovernorContract__factory";
