/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as timeLockSol from "./TimeLock.sol";
export type { timeLockSol };
export type { GovernorContract } from "./GovernorContract";
